### ISSUE TITLE
Add Code for Poznan as a partner

### ISSUE THREAD

**Issue by aniawsz** [pyladies-poland/pyladies-poland.github.io-src#13]
Add the official logo of Code for Poznan to the partners section on the main site.
Also, remove Komitywa from the section (they stopped their activity).

**Comment by juskuz** [comment]
@magul 
Where I can find the logo? Should I download it from Facebook?
I couldn't find it on Github.

**Comment by magul** [comment]
We have to determine, wha't the official logo actually. It will  take us a while, but eventually I will upload it here.

**Comment by juskuz** [comment]
@magul 
Have you already determined what's the official logo?

**Comment by magul** [comment]
@juskuz 
book of sign is here: https://drive.google.com/open?id=0B9bClCzQctIUTklpaGFfQTE5Wk0
better quality images here: https://drive.google.com/open?id=0B9bClCzQctIUZXVwUHg2MFJEZzQ
... and here: https://drive.google.com/open?id=0B9bClCzQctIUZURaTWNQYUN3ZnM
